name: Update smdd

on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#0_7_*_*_*
    - cron: "0 7 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        # with:
        #   submodules: true # This forces --depth=1 which conflicts with pull
      - uses: maximousblk/setup-deno@v1

      - name: Update submodules
        run: |
          git submodule update --init --recursive
          cd sekai-master-db-diff
          git pull --rebase origin main
          cd ..
          cd sekai-master-db-en-diff
          git pull --rebase origin main
      - name: Rewrite wikitext
        run: |
          deno run --allow-write --allow-read generators/musics.js
          deno run --allow-write --allow-read generators/events.js
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Update smdd"
          git push
      - name: Submit wikitext
        env:
          MW_LGNAME: ${{ secrets.MW_LGNAME }}
          MW_LGPASSWORD: ${{ secrets.MW_LGPASSWORD }}
        run: deno run --allow-read --allow-net --allow-env wiki.js
