name: Update smdd

on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#0_7_*_*_*
    - cron: "0 7 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        # with:
        #   submodules: true # This forces --depth=1 which conflicts with pull
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Update submodules
        run: |
          git submodule update --init --recursive
          cd sekai-master-db-diff
          git pull --rebase origin main
          cd ..
          cd sekai-master-db-en-diff
          git pull --rebase origin main
          cd ..
          cd sekai-master-db-kr-diff
          git pull --rebase origin main
      - name: Rewrite wikitext
        run: |
          deno task bonds
          deno task events
          deno task gachas
          deno task musics
      - id: git-diff
        name: Check diff on output/
        run: git diff --quiet HEAD output
        continue-on-error: true
      - name: Submit wikitext
        if: ${{ steps.git-diff.outcome == 'failure' }}
        env:
          MW_ACCESS_TOKEN: ${{ secrets.MW_ACCESS_TOKEN }}
        run: deno task wiki
      - name: Commit files
        if: ${{ steps.git-diff.outcome == 'failure' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Update smdd"
          git push
